@extends('frontend.layouts.master')

@section('title')
  Instalación y Configuración
@endsection
@section('content')
  <main>
    @include('frontend.pages.partials.category-detail-layout', [
      'heroBadge' => 'Servicio industrial · Monterrey, N.L.',
      'heroTitle' => 'Instalación y Configuración',
      'heroDescription' => 'Instalamos y configuramos controladores de temperatura, videoregistradores, medidores de flujo y sistemas PLC para tu planta industrial, con técnicos especializados y puesta en marcha documentada.',
      'stats' => [
        ['value' => '+30', 'label' => 'años en el sector industrial'],
        ['value' => '24 h', 'label' => 'respuesta en área metropolitana'],
        ['value' => '4', 'label' => 'servicios especializados'],
      ],
      'services' => [
        [
          'id' => 'temperatura',
          'n' => '01',
          'short' => 'Controladores de temperatura',
          'title' => 'Instalación y Configuración de Controladores de Temperatura',
          'description' => 'Instalamos, configuramos e integramos controladores de temperatura para hornos, calderas, extrusión, inyección, secado y refrigeración. Técnicos especializados, equipo calibrado y puesta en marcha documentada.',
          'bullets' => ['Montaje y cableado en panel', 'Configuración de entradas y alarmas', 'Sintonía PID en proceso real', 'Integración Modbus a PLC / HMI'],
          'chipsLabel' => 'Equipos que manejamos',
          'chips' => ['UDC 1200', 'UDC 1700', 'UDC 2500', 'UDC 3200', 'UDC 3500', 'Termopar J / K', 'RTD PT100'],
          'badge' => 'Instalación certificada',
          'norm' => 'Bajo normativa NOM e ISO',
          'image' => 'uploads/servicios/instalacion_controladores-1.png',
          'imageAlt' => 'Técnico instalando controlador de temperatura en tablero',
          'detailsRoute' => 'servicio-controladores-temperatura',
        ],
        [
          'id' => 'videoregistradores',
          'n' => '02',
          'short' => 'Videoregistradores',
          'title' => 'Instalación de Videoregistradores',
          'description' => 'Especialistas en grabadores de variables analógicas. Instalación profesional de registradores de datos para garantizar la confiabilidad, precisión y trazabilidad de tus procesos.',
          'bullets' => ['Cableado y configuración de canales', 'Pantallas, tendencias y alarmas', 'Exportación USB / SD / Ethernet', 'Software Trend Manager / Server Pro'],
          'chipsLabel' => 'Equipos que manejamos',
          'chips' => ['TVEZGR', 'TVMIGR', 'TVMUGR', 'Tarjetas de relevadores', 'Trend Manager Pro'],
          'badge' => 'Instalación certificada',
          'norm' => 'Bajo normativa NOM e ISO',
          'image' => 'uploads/servicios/instalacion_videoregistradores-1.png',
          'imageAlt' => 'Videoregistrador de variables analógicas en tablero industrial',
          'detailsRoute' => 'servicio-instalacion-videoregistradores',
        ],
        [
          'id' => 'flujo',
          'n' => '03',
          'short' => 'Medidores de flujo',
          'title' => 'Instalación, Configuración y Puesta en Marcha de Medidores de Flujo',
          'description' => 'Especialistas en medición de caudal. Instalamos medidores de flujo industriales para garantizar precisión, eficiencia y trazabilidad en tus procesos productivos.',
          'bullets' => ['Selección del punto de medición', 'Instalación mecánica y eléctrica', 'Configuración del transmisor', 'Verificación con flujo real'],
          'chipsLabel' => 'Equipos que manejamos',
          'chips' => ['Coriolis', 'Magnéticos', 'Ultrasónicos', 'Vortex', 'Transmisores DP', 'SMV800'],
          'badge' => 'Instalación certificada',
          'norm' => 'Bajo estándares NOM, ISO e ISA',
          'image' => 'frontend/images/servicios/medidores-flujo-transmisor-presion.jpg',
          'imageAlt' => 'Transmisor de presión Honeywell instalado en línea de proceso',
          'detailsRoute' => 'servicio-instalacion-medidoresdeflujo',
        ],
        [
          'id' => 'plc',
          'n' => '04',
          'short' => 'PLC llave en mano',
          'title' => 'Instalación, Configuración y Proyecto Llave en Mano de PLC',
          'description' => 'Servicio integral de automatización con PLC: desde el diseño del proyecto hasta la puesta en marcha, para un control fiable y eficiente de tus procesos.',
          'bullets' => ['Ingeniería y diseño de tablero', 'Programación de PLC y HMI', 'Integración de instrumentación', 'Arranque y capacitación'],
          'chipsLabel' => 'Equipos que manejamos',
          'chips' => ['HC900', 'RTU2020', 'Master Logic', 'HMI 900CR', 'Variadores MVH100'],
          'badge' => 'Proyecto llave en mano',
          'norm' => 'Bajo normativa IEC, UL y NOM',
          'image' => 'uploads/servicios/instalacion_plc-1.png',
          'imageAlt' => 'Técnico configurando un PLC en tablero de control',
          'detailsRoute' => 'servicio-instalacion-plc',
        ],
      ],
      'processBadge' => 'Cómo trabajamos',
      'processTitle' => 'Mismo método en los 4 servicios',
      'processDescription' => 'Cada etapa queda documentada para que tu equipo de mantenimiento tenga trazabilidad completa.',
      'processSteps' => [
        ['n' => '01', 'title' => 'Contacto', 'description' => 'Compartes modelo, fotos y necesidad del proceso.'],
        ['n' => '02', 'title' => 'Levantamiento', 'description' => 'Visita técnica a tablero, señales y condiciones.'],
        ['n' => '03', 'title' => 'Propuesta', 'description' => 'Cotización con alcance, tiempos y materiales.'],
        ['n' => '04', 'title' => 'Instalación', 'description' => 'Montaje, cableado y etiquetado según normativa.'],
        ['n' => '05', 'title' => 'Configuración', 'description' => 'Parámetros, alarmas y pruebas con proceso real.'],
        ['n' => '06', 'title' => 'Entrega', 'description' => 'Arranque, capacitación y documentación final.'],
      ],
      'whyBadge' => 'Por qué Mac del Norte',
      'whyTitle' => 'Distribuidor autorizado Honeywell que también instala',
      'whyDescription' => 'Suministramos el equipo y lo dejamos funcionando con el mismo proveedor: un solo responsable desde la cotización hasta la puesta en marcha.',
      'industries' => ['Tratamiento térmico', 'Calderas y vapor', 'Plásticos', 'Alimentos y bebidas', 'Farmacéutica', 'Metalmecánica', 'Tratamiento de agua', 'Químicos'],
      'values' => [
        ['title' => 'Distribuidor autorizado', 'description' => 'Honeywell y McDonnell & Miller: equipo original y refacciones.'],
        ['title' => '+30 años de experiencia', 'description' => 'Técnicos con trayectoria en instrumentación y control.'],
        ['title' => 'Respuesta en 24 h', 'description' => 'Atención rápida en el área metropolitana de Monterrey.'],
        ['title' => 'Entrega documentada', 'description' => 'Reporte, respaldo de configuración y diagramas.'],
      ],
      'faqBadge' => 'Preguntas frecuentes',
      'faq' => [
        ['q' => '¿Instalan equipos que compramos en otro lugar?', 'a' => 'Sí. Revisamos modelo y estado del equipo antes de la visita para confirmar compatibilidad.'],
        ['q' => '¿Pueden suministrar el equipo además de instalarlo?', 'a' => 'Sí. Como distribuidor autorizado Honeywell cotizamos equipo e instalación en una sola propuesta.'],
        ['q' => '¿Necesito parar la producción?', 'a' => 'Planeamos la intervención en paros programados o fines de semana para minimizar el impacto.'],
        ['q' => '¿Atienden fuera de Monterrey?', 'a' => 'Respondemos en 24 h en el área metropolitana y coordinamos visitas al resto de México; los equipos se envían a todo el país.'],
        ['q' => '¿Qué entregan al terminar?', 'a' => 'Reporte de servicio, respaldo de configuración, diagrama de conexión actualizado y capacitación al operador.'],
        ['q' => '¿Cómo cotizo?', 'a' => 'Envíanos por WhatsApp modelo, fotos del equipo o tablero y una breve descripción del proceso.'],
      ],
      'ctaTitle' => 'Envíanos foto de tu equipo o tablero',
    ])
  </main>
@endsection
